name: test1-buildingblocks
on: 
  push:
  schedule:
    - cron: '* * * 1 *'

jobs: 
  echo-hello:
    runs-on: ubuntu-latest
    steps: 
      - name: Say hello 
        run: echo "hello world"
  
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: good bye
        run: echo "good bye"
    