name: test2Workflow-test
on: 
    push:
    pull_request: 
    schedule:
      - cron: '5 5 * * *'
    workflow_dispatch: 

jobs:
  echoEvent: 
    runs-on: ubuntu-latest
    steps:
      - name: trying to print github event name 
        run: echo "i am triggered with ${{github.event_name}} event and OS is ${{runner.os}}"
        